# Generated by Django 3.1.14 on 2022-05-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
