# Generated by Django 3.1.14 on 2022-05-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_logentry_updated'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['created', 'body'], name='super_log_entry_idx'),
        ),
    ]
